table GQP
	lineageTag: 33ca53ff-9380-4034-aeb9-e1359778ac7e

	column Page
		dataType: int64
		formatString: 0
		lineageTag: d047d2fc-2294-4056-8b00-02280b84cfed
		summarizeBy: none
		sourceColumn: Page

		annotation SummarizationSetBy = Automatic

	column Text
		dataType: string
		lineageTag: 8bd4e910-6014-4b9d-9513-c47021bbbc5b
		summarizeBy: none
		sourceColumn: Text

		annotation SummarizationSetBy = Automatic

	column filename
		dataType: string
		lineageTag: d6abc14b-97fa-4783-b266-fa9a3a0e9224
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	column Corrected_Text
		dataType: string
		lineageTag: 15d8397e-8eb7-4583-b66a-29caf649b062
		summarizeBy: none
		sourceColumn: Corrected_Text

		annotation SummarizationSetBy = Automatic

	partition GQP = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\cmorr\GQP_DEV\MassDEPGQP-1\uploads\ATTACHMENT_649114.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Page", Int64.Type}, {"Text", type text}, {"filename", type text}, {"Corrected_Text", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

