table PageNumber
	lineageTag: b52f9c44-b7bf-401a-8621-8e554ce43c46

	measure 'PageNumber Value' = SELECTEDVALUE('PageNumber'[PageNumber])
		formatString: 0
		lineageTag: 268d698b-0dcc-412a-9dd5-d3b868617554

	column PageNumber
		formatString: 0
		lineageTag: d2d7b82f-4e0f-4885-a5cf-42a4d9c09e08
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition PageNumber = calculated
		mode: import
		source = GENERATESERIES(1, 77, 1)

	annotation PBI_Id = e7a3fcae2f9948e586b86e1b93edef8b

